version: '3.1'
services:
  test:
    image: openjdk:11.0-jdk-slim
    working_dir: /api
    depends_on:
      - mongodb
    environment:
      - GRADLE_OPTS="-Xmx1g"
      - DB_HOST="localhost"
      - DB_PORT=27018
      - DB_DATABASE="test"
      - DB_USERNAME="user"
      - DB_PASSWORD="secret"
    command: >
      make test
  mongodb:
    image: mongo:3.6.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: test
    ports:
      - "27018:27017"
