version: '3'
services:
  back-api:
    container_name: api-back
    image: build-back
    working_dir: /api
    env_file:
      - ./.env
    depends_on:
      - mongodb-gg
    environment:
      DB_HOST: mongodb-gg
    ports:
      - 8080:8080
  mongodb-gg:
    container_name: mongodb-gg
    image: mongo:3.6.8
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    ports:
      - 27017:27017
    volumes:
    - ./database:/database
