version: '3.1'
services:
  back-api:
    image: openjdk:11.0-jdk-slim
    working_dir: /api
    external_links:
      - mongodb_local
    environment:
      - GRADLE_OPTS="-Xmx1g"
      - DB_HOST="localhost"
      - DB_PORT=27017
      - DB_DATABASE="desafio_walmart"
      - DB_USERNAME="brandDiscountsUser"
      - DB_PASSWORD="brandDiscountsPassword"
    command: >
      make run
