version: '3'
services:
  back-api:
    container_name: api-back
    image: app-build-back
    working_dir: /api
    env_file:
      - ./.env
    depends_on:
      - mongodb-local
    environment:
      DB_HOST: mongodb-local
    ports:
      - 8080:8080
  mongodb-local:
    container_name: mongodb-local
    image: mongo:3.6.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: brandDiscountsUser
      MONGO_INITDB_ROOT_PASSWORD: brandDiscountsPassword
      MONGO_INITDB_DATABASE: desafio_walmart
    ports:
      - 27017:27017
    volumes:
    - ./database:/database
