version: '3.1'
services:
  mongodb-test:
    image: mongo:3.6.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: test
    ports:
      - "27018:27017"
